### PR TITLE
Fixed QT6 and macOS build errors

### PR DESCRIPTION
**Pull request by Kreeblah**
I noticed that this wouldn't compile against QT6, and there seemed to be some issues with how libusb was called.  This fixes those problems.

### CODE REVIEW

**Comment by radiomanV** [comment]
Sorry, but can you explain to me what's wrong with `some issues with how libusb was called`? It is legal to pass null for the default context: https://libusb.sourceforge.io/api-1.0/libusb_contexts.html. The initial approach was like yours but i have changed to nullptr some time ago.
The QT6 fixes are okay. Thanks!

**Comment by Kreeblah** [comment]
The issue wasn't with `nullptr` specifically.  It was that on line 52, there's a reference to `ctx` which isn't defined.  So, I added a definition for that.  I suppose changing that line to `nullptr` rather than adding a `ctx` definition would have worked just as well, though.

**Comment by Kreeblah** [comment]
OK, I just switched back to `nullptr` for the context, and used that for line 52 in `usb_macos.cpp` as well.

**Comment by radiomanV** [comment]
Oh, you're absolutely right. As i don't use macos i never encountered this error. Thanks for clarifications. I'll merge this.

**Comment by radiomanV** [comment]
Also a small fix, we need to set the background role for all those labels used as leds otherwise they're all set to grey color (at least in my Linux distro). It seems that QT6 introduced some changes and requirements not present in the previous versions. Meh, i never liked Qt but that is.

**Pull request merged**
